server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: 4530873kopq
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect